/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package converter;

import javax.swing.JOptionPane;

/**
 *
 * @author Sanchit Chopra
 */
public class main_ui extends javax.swing.JFrame {
    
    String[] symbols ={
    " ",
    "R$",
    "€",
    "₨",
    "$",
    "¥",
    "C$",
    "₹",
    "₮",
    "£",
    "₩"
};
    //amt in RAND
    double Brazil_money=0.27;
    double Europe_money=0.050;
    double Pakistan_money=15.52;
    double USA_money=0.055;
    double Japan_money=7.43;
    double Canada_money=0.075;
    double India_money=4.54;
    double Mongolia_money=195.30;
    double UK_money=0.045;
    double Korea_money=72.39;


    /**
     * Creates new form main_ui
     */
    public main_ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toamt = new javax.swing.JComboBox<>();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        fromsym = new javax.swing.JLabel();
        tosym = new javax.swing.JLabel();
        convertamt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromamt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(666, 465));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(666, 466));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 63, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(666, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("AMOUNT CONVERTING FROM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("AMOUNT CONVERTING TO ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 22));

        toamt.setBackground(new java.awt.Color(109, 122, 138));
        toamt.setForeground(new java.awt.Color(255, 255, 255));
        toamt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "R$-Brazil", "€-Europe", "₨-Pakistan", "$-USA", "¥-Japan", "CA$-Canada", "₹-India", "₮-Mongolia", "£-UK", "₩-Korea" }));
        toamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toamtActionPerformed(evt);
            }
        });
        jPanel1.add(toamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        txt1.setBackground(new java.awt.Color(109, 122, 138));
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 57, -1));

        txt2.setBackground(new java.awt.Color(109, 122, 138));
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 57, -1));

        fromsym.setBackground(new java.awt.Color(255, 255, 255));
        fromsym.setText("   ");
        jPanel1.add(fromsym, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 24, 22));

        tosym.setBackground(new java.awt.Color(255, 255, 255));
        tosym.setText("   ");
        jPanel1.add(tosym, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 24, 22));

        convertamt.setBackground(new java.awt.Color(0, 168, 135));
        convertamt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        convertamt.setForeground(new java.awt.Color(255, 255, 255));
        convertamt.setText("CONVERT");
        convertamt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertamtMouseClicked(evt);
            }
        });
        jPanel1.add(convertamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jButton1.setBackground(new java.awt.Color(195, 192, 187));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 97, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 97, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ENTER AMOUNT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 118, 38));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/converter/Untitled.jpeg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(666, 456));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 550));

        fromamt.setBackground(new java.awt.Color(109, 122, 138));
        fromamt.setForeground(new java.awt.Color(255, 255, 255));
        fromamt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "R$-Brazil", "€-Europe", "₨-Pakistan", "$-USA", "¥-Japan", "CA$-Canada", "₹-India", "₮-Mongolia", "£-UK", "₩-Korea" }));
        fromamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromamtActionPerformed(evt);
            }
        });
        jPanel1.add(fromamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, 22));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 50, 670, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void convertamtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertamtMouseClicked
        // TODO add your handling code here:
        if (fromamt.getSelectedIndex()==0  || toamt.getSelectedIndex()==0 || txt1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the Country and Amount",
                "Error Message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        double amttochange = Double.parseDouble(txt1.getText());
        double amtdefault= 0.0;
        double amtindefault = 0.0;
        
        switch(fromamt.getSelectedItem().toString())
        {
            case "R$-Brazil": amtindefault =amttochange/Brazil_money;break;
            case "€-Europe": amtindefault =amttochange/Europe_money;break;
            case "₨-Pakistan": amtindefault =amttochange/Pakistan_money;break;
            case "$-USA": amtindefault =amttochange/USA_money;break;
            case "¥-Japan": amtindefault =amttochange/Japan_money;break;
            case "C$-Canada": amtindefault =amttochange/Canada_money;break;
            case "₹-India": amtindefault =amttochange/India_money;break;
            case "₮-Mongolia": amtindefault =amttochange/Mongolia_money;break;
            case "£-UK": amtindefault =amttochange/UK_money;break;
            case "₩-Korea": amtindefault =amttochange/Korea_money;break;
        }
        
        switch(toamt.getSelectedItem().toString()) {
            case "R$-Brazil": amtdefault =amtindefault * Brazil_money; break;
            case "€-Europe": amtdefault =amtindefault * Europe_money; break; 
            case "₨-Pakistan": amtdefault =amtindefault * Pakistan_money; break; 
            case "$-USA": amtdefault =amtindefault * USA_money; break;
            case "¥-Japan": amtdefault =amtindefault* Japan_money; break;
            case "C$-Canada": amtdefault = amtindefault * Canada_money; break;
            case "₹-India": amtdefault =amtindefault * India_money; break;
            case "₮-Mongolia": amtdefault =amtindefault * Mongolia_money; break;
            case "£-UK": amtdefault =amtindefault * UK_money; break;
            case "₩-Korea": amtdefault =amtindefault * Korea_money; break;
        }
        
        String value=String.format("%.2f",amtdefault);
        txt2.setText(value);
    }//GEN-LAST:event_convertamtMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fromamt.setSelectedIndex(0);
        toamt.setSelectedIndex(0);
        txt1.setText(null);
        txt2.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fromamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromamtActionPerformed
        // TODO add your handling code here:
        int pos=fromamt.getSelectedIndex();
        fromsym.setText(symbols[pos]);
    }//GEN-LAST:event_fromamtActionPerformed

    private void toamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toamtActionPerformed
        // TODO add your handling code here:
        int pos=toamt.getSelectedIndex();
        tosym.setText(symbols[pos]);
    }//GEN-LAST:event_toamtActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertamt;
    private javax.swing.JComboBox<String> fromamt;
    private javax.swing.JLabel fromsym;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> toamt;
    private javax.swing.JLabel tosym;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
